import Head from 'next/head'
import Navigation from './Navigation'

const GuestLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Laravel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation user={null} />

      {children}
    </>
  )
}

export default GuestLayout
