import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { CgArrowLongLeft } from 'react-icons/cg'
import React, { lazy, Suspense } from 'react'
import AppLayout from '@/components/Layouts/AppLayout'

const Tab: NextPage = () => {
  const router = useRouter()
  const [Tab, setTab] = React.useState<any>('')

  const MyComponent = lazy(() =>
    import(
      `@/components/pages/settings/${Tab}/${
        Tab.charAt(0).toUpperCase() + Tab.slice(1)
      }`
    ).catch(() => ({ default: () => <div className="px-6">Not found</div> })),
  )

  React.useEffect(() => {
    setTab(router.query.tab)
    console.log(MyComponent)
  }, [router.isReady])

  return (
    <AppLayout>
      <main className="container py-20 ">
        <Head>
          <title>
            Titan {Tab ? '| ' + Tab.charAt(0).toUpperCase() + Tab.slice(1) : ''}
          </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className="ml-6 pb-4 w-32">
          <Link href="/settings">
            <a className="text-sm text-indigo-600 flex items-center gap-1">
              <CgArrowLongLeft size={22} /> Your Account
            </a>
          </Link>
        </header>

        <Suspense fallback={<h1 className="px-6">Loading...</h1>}>
          {Tab && <MyComponent />}
        </Suspense>
      </main>
    </AppLayout>
  )
}

export default Tab
