import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Importimages from '@/hooks/Importimages'
import Link from 'next/link'
import AppLayout from '@/components/Layouts/AppLayout'

const Images = Importimages(
  require.context(`@/assets/svg/settings`, true, /\.(png|jpe?g|svg)$/),
)

const ListItem = [
  {
    id: 0,
    name: 'Your Orders',
    description: 'Track, return, or cancel',
    image: Images[4],
    url: 'settings/orders',
  },

  {
    id: 1,
    name: 'Personal Info',
    description: 'View and edit your personal info',
    image: Images[5],
    url: 'settings/account',
  },

  {
    id: 2,
    name: 'Password',
    description: 'Change your password',
    image: Images[2],
    url: 'settings/password',
  },

  {
    id: 3,
    name: 'Your Addresses',
    description: 'Edit or add a shipping address',
    image: Images[1],
    url: 'settings/addresses',
  },

  {
    id: 4,
    name: 'Payment methods',
    description: 'Add or remove payment methods',
    image: Images[3],
    url: 'settings/payments',
  },

  {
    id: 5,
    name: 'Contact Us',
    description: 'Contact via phone or chat',
    image: Images[0],
    url: 'settings/contact',
  },
]

const Settings: NextPage = () => {
  return (
    <AppLayout>
      <main className="container py-20">
        <Head>
          <title>Titan | Settings</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <>
          <h1 className="px-6 py-4 text-lg font-semibold">Your Account</h1>

          <section className="px-6 pb-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 items-center gap-6">
            {ListItem.map(item => {
              return (
                <Link href={item.url}>
                  <a
                    className="flex items-center border p-3 rounded-2xl gap-2.5 hover:bg-gray-50 cursor-pointer bg-white"
                    key={item.id}>
                    <div>
                      <img src={item.image} alt="" className="w-9" />
                    </div>

                    <div>
                      <h1 className="font-semibold">{item.name}</h1>
                      <p className="text-sm text-gray-600">
                        {item.description}
                      </p>
                    </div>
                  </a>
                </Link>
              )
            })}
          </section>
        </>
      </main>
    </AppLayout>
  )
}

export default Settings
