import type { NextPage } from 'next'
import Head from 'next/head'
import { RiHeart3Line } from 'react-icons/ri'
import Colour from '../components/ui/cart/Colour'

import { CgArrowLongLeft, CgTrashEmpty } from 'react-icons/cg'
import Size from '../components/ui/quickview/Details/Size'
import Quantity from '../components/ui/quickview/Details/Quantity'
import Link from 'next/link'
import GuestLayout from '@/components/Layouts/GuestLayout'

const CartItem = () => {
  return (
    <div className="flex flex-wrap gap-4 py-4 items-start">
      <div>
        <img
          src="https://cdn.outfitbook.fr/26317-thickbox_default/jogger-short-dark-green.jpg?_ga=2.61955052.1799479511.1662785947-1104294664.1662785947"
          alt=""
          className="w-24 object-cover rounded-lg"
        />
      </div>
      <div className="translate-y-1.5">
        <h1 className="text-lg font-semibold">Product Name</h1>
        <div className="flex gap-2 items-center mb-2">
          <p className="font-semibold">$12 | </p>
          <p className="font-normal text-indigo-600 text-sm">In Stock</p>
        </div>
        <div className="flex gap-5 md:gap-8 items-center flex-wrap">
          <div className="flex gap-3 items-center">
            <Size />
            <Colour />
            <Quantity />
          </div>
          <div className="flex items-center gap-4 md:translate-y-2.5">
            <button className="flex items-center gap-1 text-sm">
              <RiHeart3Line size="22" className="text-gray-500" /> Save
            </button>
            <button className="flex items-center gap-1 text-sm">
              <CgTrashEmpty size="22" className="text-gray-500" /> Delete
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
const Cart: NextPage = () => {
  return (
    <GuestLayout>
      <main className="container py-20">
        <Head>
          <title>Titan | Cart</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className="bg-white p-5 rounded-xl">
          <section className="flex justify-between px-2">
            <h1 className="text-xl mb-3 font-semibold">Cart</h1>
            <h1 className="text-xl mb-3 font-semibold">Total: $150</h1>
          </section>
          <section className="px-3 rounded-xl">
            <CartItem />
            <CartItem />
            <CartItem />
          </section>

          <section className="flex justify-between py-5 px-3 items-center">
            <Link href={'/category'}>
              <a className="flex items-center gap-1 text-gray-500 text-sm">
                <CgArrowLongLeft size={24} /> Back to shop
              </a>
            </Link>

            <Link href={'/checkout'}>
              <a className="bg-indigo-600 text-white h-10 px-4 rounded-md flex justify-center w-32 items-center gap-1">
                Checkout
              </a>
            </Link>
          </section>
        </header>
      </main>
    </GuestLayout>
  )
}

export default Cart
