import GuestLayout from '@/components/Layouts/GuestLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Filter from '../components/pages/category/filter/Filter'
import Products from '../components/pages/category/Products'

const Category: NextPage = () => {
  return (
    <GuestLayout>
      <main className="container pt-16">
        <Head>
          <title>Titan | Products</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Filter />
        <Products />
      </main>
    </GuestLayout>
  )
}

export default Category
