import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import Payment from '../components/pages/checkout/Payment/Payment'
import ShoppingCart from '../components/pages/checkout/ShoppingCart'
import ShoppingInfo from '../components/pages/checkout/shoppinginfo/ShoppingInfo'
import AppLayout from '@/components/Layouts/AppLayout'

const Checkout: NextPage = () => {
  const [Shoppinginfo, setShoppingInfo] = React.useState<boolean>(true)
  const [PaymentSelection, setPaymentSelection] = React.useState<boolean>(false)
  return (
    <AppLayout>
      <main className="container py-4">
        <Head>
          <title>Titan | Checkout</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
          <section className="border-b mb-8">
            <ul className="flex gap-10 items-center">
              <li
                className={` ${
                  Shoppinginfo
                    ? 'border-b-2 border-indigo-600 py-3'
                    : 'text-gray-500'
                }`}>
                01 Shopping Info
              </li>
              <li
                className={`${
                  PaymentSelection
                    ? 'border-b-2 border-indigo-600 py-3'
                    : 'text-gray-500'
                }`}>
                02 Payment Selection
              </li>
            </ul>
          </section>
          <ShoppingCart />

          {Shoppinginfo && (
            <ShoppingInfo
              setShoppingInfo={setShoppingInfo}
              setPaymentSelection={setPaymentSelection}
            />
          )}

          {PaymentSelection && (
            <Payment
              setShoppingInfo={setShoppingInfo}
              setPaymentSelection={setPaymentSelection}
            />
          )}
        </header>
      </main>
    </AppLayout>
  )
}

export default Checkout
